### ISSUE TITLE
how to start this. when running  'node example.js' in terminal

### ISSUE THREAD

**Issue by chrisluwtw** [AlphaReign/dht-server#11]
Error: bind EADDRINUSE 0.0.0.0:6881
    at state.handle.lookup (dgram.js:242:18)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at DHT.onError (/opt/dht-server/src/index.js:120:8)
    at Socket.DHT.socket.on (/opt/dht-server/src/index.js:45:43)
    at Socket.emit (events.js:198:13)
    at state.handle.lookup (dgram.js:243:14)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Raxvis** [comment]
That means the port is already being used by something else.  You will need to look at your open ports and figure out what program is already using that port

**Comment by chrisluwtw** [comment]
thanks, let me try that

**Comment by chrisluwtw** [comment]
btw, do you need to use this DHT Server together with Scraper?  what is the difference between them?

**Comment by Raxvis** [comment]
The DHT Server is just a normal DHT Server that behaves accordingly.  The Scraper just crawls the DHT Network looking for hashes.  Originally, the plan was to build a robust DHT Server, and then build a scraper on top of it, so that the scraper only needed scraping code and no DHT code

**Comment by St0RM53** [comment]
Sorry to hijack this thread here, i really loved AlphaReign and after you closed it down i was wondering if i can just run it locally (my PC is running 24h either way) and have my own private torrent scrapper;
However i haven't tried it because i don't know if it will work...if you say yes i think i will try it out
